Clarification on restrictions
InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework pull request #244
Opened 2020-09-19 11:14 UTC by asr-enid

As discussed in https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/220 - some more explicit description in the section "What are publisher restrictions?". Looking at the discussion it seem good to make it more explicit 

- when which restrictions must be applied when
- to explicitly state that the default must always be applied in the absence of a signal
- legal basis signal without vendor flexibility are redundant.

@chrispaterson the TC Core String details description contains some langes in the notes that restrictions **should** be respected even without flexibility, not sure I you'd want to change that given the code would not even allow them to be written just now

2020-09-19 12:18 UTC, asr-enid commented
Adding here - the language around default legal basis is already present in the spec, but just in the annotated example global vendor list - seem even more reasonable to give this a bit more visibility. What missing here is that the default can only be changes via a restriction.

`
   * "legIntPurposes" conditionally OPTIONAL (see "Constraints") array of
   * positive integers. List of Purpose ids declared as performed on the legal
   * basis of legitimate interest
   *
   * "flexiblePurposes": OPTIONAL array of positive integers. Array may be
   * empty. List of purpose ids where the vendor is flexible regarding the
   * legal basis; they will perform the processing based on consent or a
   * legitimate interest. **The 'default'** is determined by which of the other two
   * mutually-exclusive purpose fields is used to declare the purpose for the
   * vendor
   *
 * Constraints:
   *   Either purposes OR legIntPurposes can be missing/empty, but not both.
   *
   *   A Purpose id must not be present in both purposes and legIntPurposes
   *
   *   A Purpose id listed in flexiblePurposes must have been declared in one
   *   of purposes or legIntPurposes.
   *
   *   Purpose id values included in the three purpose fields must be in the
   *   range from 1 to N, where N is the highest purpose id published in this
   *   GVL file.`

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#example-global-vendor-list-json-object

2020-09-28 15:38 UTC, Facens commented
@asr-enid thanks, the changes look good to me. What about also adding to the CMP guidelines that CMPs can avoid sending redundant information, as per the gdoc here? https://docs.google.com/document/d/1yoYN-iD7wlLjPt1DyEYN8KFAyiO_yZGk_CWhiWOnqAI/edit?disco=AAAAG15TmLU&ts=5f720228&usp_dm=false
I can review if you take the lead and add it, so we can get this moving forward quickly. Thanks!

2020-09-29 07:39 UTC, asr-enid commented
@Facens - you mean within the general implementation guidelines? https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/TCF-Implementation-Guidelines.md#cmp

2020-09-29 07:41 UTC, Facens commented
@asr-enid Yes! This is what we've agreed on the latest group meeting.

2020-09-29 07:42 UTC, asr-enid commented
Ok - will add something to this pull request (makes sense given its the same context), would like to get this closed

2020-09-29 12:04 UTC, asr-enid commented
Added some language in the implementation guidelines to reflect in which cases restrictions are necessary. Added some language that this does not preclude encoding schemes that might deviate (as suggested by @chrispaterson ) from this because they might be more space efficient with the same results

2020-09-30 11:14 UTC, asr-enid commented
@Facens - let me know what you think - I'd find it highly valuable to have both clarifications merged soon.

2020-09-30 12:24 UTC, Facens requested changes

2020-09-30 12:24 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +CMPs are advised to store/provide publisher restrictions only in cases they are necessary to reflect the publishers choice to restrict a vendors processing of personal data. In terms of reflecting a
```suggestion
In order to reduce the size of the TC string, CMPs are advised to store/provide publisher restrictions only when necessary to reflect the publisher's choice to restrict a vendor's processing of personal data. In terms of reflecting a publisher’s choice:
```

2020-09-30 12:24 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +* In case a vendor has not been disclosed to the user via the CMP UI, there is no need to store restrictions for that vendor in the TC String. Given the vendor was not disclosed both vendor consent a
must be set to 0 -> can be left undefined?

2020-09-30 12:24 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +* Purpose restrictions (i.e. disallowing a vendor to process) need to be stored in case the vendor was disclosed by the CMP (reflecting the restriction in the UI) and registered for that purpose in t
Not sure I follow this one. I think you're referring to restricting a purpose for a specific vendor, in which case the restrictions{} must be passed with a disallowed. If so it should be clarified.

2020-09-30 12:24 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +* Legal Basis restrictions are only needed in situations where there vendor was disclosed by the CMP (reflecting the restriction in the UI)  and declared flexibilty in the GVL for the respective purp
```suggestion
* Legal Basis restrictions are only needed in situations where there vendor was disclosed by the CMP (reflecting the restriction in the UI) and declared flexibilty in the GVL for the respective purpose, meaning:
```

2020-09-30 12:24 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +    1. The vendor registered a purpose as legitimated interest (default legal basis), but also registered this purpose as flexible (i.e. also accepts consent as a legal basis). In this case a "requir
```suggestion
    1. The vendor registered a purpose as legitimate interest (default legal basis), but also registered this purpose as flexible (i.e. also accepts consent as a legal basis). In this case a "require consent" restriction is needed to signal that the vendor may only apply the consent signal/can rely on it to process personal data.
```

2020-09-30 12:24 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +Note that the above does not preclude the use of efficient encoding/decoding schemes in certain scenarios, for example in cases where a publisher wants to restrict a purpose for all vendors to consen
```suggestion
Note that the above does not preclude the use of efficient encoding/decoding schemes in certain scenarios, for example in cases where a publisher wants to restrict a purpose for all vendors to consent it might be more efficient to encode a small number of range restriction segments using a specific encoding scheme.
```

2020-09-30 18:21 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +Note that the above does not preclude the use of efficient encoding/decoding schemes in certain scenarios, for example in cases where a publisher wants to restrict a purpose for all vendors to consen
It looks like there is alignment here. I'd like to merge this in by the end of the work week. Do you think we're there?

2020-09-30 19:31 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +* In case a vendor has not been disclosed to the user via the CMP UI, there is no need to store restrictions for that vendor in the TC String. Given the vendor was not disclosed both vendor consent a
Fine for me, adapted accordingly

2020-09-30 19:31 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +* Purpose restrictions (i.e. disallowing a vendor to process) need to be stored in case the vendor was disclosed by the CMP (reflecting the restriction in the UI) and registered for that purpose in t
This is the same language as used in the TC String Format descriptions, a restrictions is either 

1. **Purpose** restrictions -> a vendor is disallowed to process for a purpose 
2. **Legal Basis** restrictions -> a vendor is forced to use a different legal basis and may not rely on its default one

Changed the language to make this clearer

2020-09-30 19:44 UTC, asr-enid commented
@alextcone I'm good - accepted the suggested changed from @Facens and changed the language on purpose restrictions as well as leaving vendor bits undefined rather them setting them to 0 (last commit).

2020-10-01 15:48 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +* In case a vendor has not been disclosed to the user via the CMP UI, there is no need to store restrictions for that vendor in the TC String. Given the vendor was not disclosed both vendor consent a
```suggestion
* In case a vendor has not been disclosed to the user via the CMP UI, there is no need to store restrictions for that vendor in the TC String. If the vendor was not disclosed, both vendor consent and vendor legitimate interest signals in the TC String can be left undefined which suffices to signal that the vendor may not process personal data.
```

2020-10-01 15:50 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +* Legal Basis restrictions are only needed in situations where there vendor was disclosed by the CMP (reflecting the restriction in the UI) and declared flexibilty in the GVL for the respective purpo
```suggestion
* Legal Basis restrictions are only needed in situations where the vendor was disclosed by the CMP (reflecting the restriction in the UI) and had declared flexibility in the GVL for the corresponding purpose, meaning:
```

2020-10-01 15:53 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +    1. The vendor registered a purpose as legitimate interest (default legal basis), but also registered this purpose as flexible (i.e. also accepts consent as a legal basis). In this case a "require
```suggestion
    1. The vendor registered a purpose as legitimate interest (default legal basis), but also registered this purpose as flexible (i.e. also accepts consent as a legal basis). In this case a "require consent" restriction is needed to signal that the vendor may only process using consent as legal basis.
```

2020-10-01 15:54 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +    2. The vendor registered a purpose as consent (default legal basis), but also registered this purpose as flexible (i.e. also accepts legitimate interest as a legal basis).  In this case a "requir
```suggestion
    2. The vendor registered a purpose as consent (default legal basis), but also registered this purpose as flexible (i.e. also accepts legitimate interest as a legal basis).  In this case a "require legitimate interest" restriction is needed to signal that the vendor may only process using legitimate interest as legal basis.
```

2020-10-01 15:54 UTC, alextcone reviewed
I only have one comment to be resolved. Otherwise I am happy with this and appreciate the work you've put into this.

2020-10-01 15:54 UTC, alextcone commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
I feel like this bullet does not sufficiently achieve the aim of "avoidance of doubt". I under stand what you're getting at I think, but I think this bullet can either be struck or it should have a qualifier like "...who will determine whether or not processing is allowed based on x, y, z."

2020-10-01 15:54 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +## 5. Encoding publisher restrictions <a name="pubrestrenc"></a>
I am happy with this section. I think it does the job we're aiming to do in clarifying how a CMP should operate here.

2020-10-01 15:55 UTC, Facens requested changes

2020-10-01 15:55 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +Note that the above does not preclude the use of efficient encoding/decoding schemes in certain scenarios, for example in cases where a publisher wants to restrict a purpose for all vendors to consen
```suggestion
Note that the above does not preclude the use of efficient encoding/decoding schemes in certain scenarios. For example, in cases where a publisher wants to restrict a purpose for all vendors to consent, it might be more efficient to encode a small number of range restriction segments using a specific encoding scheme.
```

2020-10-01 16:01 UTC, Facens commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
@alextcone not sure I follow, could you explain? The gist here is:
- If you declare a certain purpose under "purposes", thus with "consent" as your default legal basis, you can only fall back to legitimate interest for that purpose if you had declared it as flexible and if you're getting "2" for that purpose under restrictions {}
- If you declare a certain purpose under "legIntPurposes", thus with "legitimate interest" as your default legal basis, you can only fall back to consent for that purpose if you had declared it as flexible and if you're getting "1" for that purpose under restrictions {}
Maybe it's clearer if we put it this way? Or we could just add the above for EXTRA clarity.

2020-10-01 17:48 UTC, alextcone commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
Anything that says a vendor can "ignore" something that isn't further qualified to say "but you can only ignore this part" makes me nervous about potential interpretations. This last bullet is the one I am concerned about:

> Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors

2020-10-01 17:51 UTC, Facens commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
I don't think that part is instrumental, it's more like a deduction, we could also remove it.
@asr-enid?

2020-10-01 18:54 UTC, alextcone commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
I think if you're ok with removing it I am too. The explainers above make it clear in my mind. If we're going to keep it though we need to finish the thought.

2020-10-02 06:48 UTC, asr-enid commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
I think @alextcone is only refering to 

> Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors

We can strike that bullet no objection from my end

2020-10-02 06:57 UTC, asr-enid commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
Ok with removing, I added this with a different topic in mind which is not relevant here. Will take care of it

2020-10-02 07:09 UTC, asr-enid commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +* Restriction signals with respect to applicable legal basis for purposes for which a vendor has not declared flexibility may be ignored by vendors
See commit https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/244/commits/d74f1fad0468c81c616bb06f40f6c310c8245b77

2020-10-02 07:18 UTC, Facens commented
@asr-enid Take a look at my comments too, all minor tweaks in English, my bad for not creating a review and filing them as single comments, thought I could convert them but can't find a way. Lmk!

2020-10-02 07:18 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +* In case a vendor has not been disclosed to the user via the CMP UI, there is no need to store restrictions for that vendor in the TC String. Given the vendor was not disclosed both vendor consent a
Would want to leave it like that, sentence one is already defining that the vendor was not disclosed, thus 2 picks of on that (In case...., If.... is double conditional here)

2020-10-02 07:27 UTC, asr-enid commented
I think we are good now, also applied the editorial comments (all but one) in https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/244/commits/30f1686167747549e624380110ecc1d4412ca91f

2020-10-02 07:43 UTC, Facens commented
I think we're good! @alextcone FF to give it a final read and merge!

2020-10-02 15:34 UTC, alextcone approved these changes
Looks good. Thank you! Merging now.

2020-10-02 15:36 UTC, merged