Update implementation guidelines for vendor
InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework pull request #253
Opened 2020-11-16 11:13 UTC by asr-enid

Action item from the Global Privacy Working Group Call 11/12/20. Pulled together details about legal basis determination from the TC String Format description (mainly Core String Details w.r.t. restriction signals), added as a new segment in the guidance (did not contain any details on this prior)

2020-11-16 15:20 UTC, alextcone requested changes
@asr-enid - thank you for advancing this work. I just have a few grammar suggestions.

2020-11-16 15:20 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +In case the publisher disallowed processing or the publisher defined legal basis is not registered by the vendor nor is the vendor flexible it may not process for that purpose. As an example, if a ve
First sentence:
change "disallowed" to "disallows" (prefer present tense where possible)
Second sentence:
change "As an example" to "For example"
change "legitimated" to "legitimate" 
remove "" from "require consent"

2020-11-16 15:20 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +Only if both signals are present for the applicable legal basis in the TC String, the vendor may then process for that purpose.
Reword sentence to:
Only if both signals are present for the applicable legal basis in the TC String  may the vendor process for that purpose.

2020-11-16 15:20 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor witho
First sentence:
add "the" in front of "policies"
In general:
This block of text should be reviewed by IAB Europe. I believe it is accurate, but it's good to be sure that the language matches what can be found in the policies.

2020-11-16 15:20 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor witho
I'm actually seeing that this is how the text currently reads. I do not love it, but you can disregard my comment ablve.

2020-11-16 15:40 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +Only if both signals are present for the applicable legal basis in the TC String, the vendor may then process for that purpose.
Thx. works

2020-11-16 15:40 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor witho
Hi Alex - I only adapted they heading of this, this part is already in the current implementation guideline.

2020-11-16 22:25 UTC, berjayasompo requested changes
Test

2020-11-19 13:43 UTC, alextcone approved these changes
Thanks @asr-enid!

2020-11-19 13:46 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
I just noticed two things:
# the last sentence is incomplete
# "see" link is broken

2020-11-19 13:47 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
@asr-enid - what did you mean to link to?

2020-11-19 13:48 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
Checking

2020-11-19 13:49 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
I just wanted to link to the previous paragraph, given the Vendor A would check for Vendor B as described in how to determine a legal basis.

2020-11-19 13:51 UTC, alextcone commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
Ok, I can make this change.

2020-11-19 13:52 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
Okay thanks

2020-11-19 13:56 UTC, alextcone commented
I'm going to seek one more approval via the Global Privacy Working Group today and then will merge. Thanks for spearheading this, @asr-enid.

2020-11-19 14:05 UTC, asr-enid commented
Looks good - feel free to merge

2020-11-24 07:36 UTC, Facens requested changes

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +For vendors or media buyers registered in the Global Vendor List, these guidelines help you understand how to determine whether you have the necessary legal bases to process a user's personal data fo
```suggestion
For vendors or media buyers registered in the Global Vendor List, these guidelines help you understand how to determine whether you have the necessary legal bases to process a user's personal data for the purposes you've disclosed in the GVL, based on the information contained in the TC String.
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +1.	Vendors must be registered in the Global Vendor List if they want to read or process user data in compliance with TCF or store and/or access information on a user’s device in compliance with the T
```suggestion
1.	In order to read or process user data in compliance with the TCF or store and/or access information on a user’s device in compliance with the TCF, vendors must be registered in the Global Vendor List. 
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +In order to determine if they have the necessary legal basis to process a user’s personal data for a specific purpose registered in the GVL, vendors must apply all relevant signals from the TC String
```suggestion
In order to determine if they have the necessary legal basis to process a user’s personal data for a specific purpose registered in the GVL, vendors must follow all relevant signals from the TC String in accordance with what they disclose in the GVL. 
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +The relevant signals are: The applicable version of the GVL, the publisher restriction signal, the purpose legal basis signal and the vendor legal basis signal.
```suggestion
The relevant signals in the TC string are the GVL version, the publisher restrictions signal, the purpose legal basis signal and the vendor legal basis signal.
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +Prior to processing a user’s personal data for a purpose registered in the GVL, vendors must:
```suggestion
Prior to processing a user’s personal data for a purpose registered in the GVL, for each purpose vendors must:
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +1.  Check if the publisher disallowed the processing for this purpose using a purpose restriction
```suggestion
1.  Check if the publisher completely disallowed processing based on this purpose using a purpose restriction 
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +2.  Check if the publisher specified the applicable legal basis for this purpose using a legal basis restriction:
```suggestion
2.  Check if the publisher restricted the applicable legal basis for this purpose using a legal basis restriction (e.g. the publisher only allows "consent" as legal basis for this purpose, or only allows "legitimate interest" as legal basis for this purpose):
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +    -  In the absence of a legal basis restriction vendors must apply their default legal basis
```suggestion
    -  In the absence of a legal basis restriction, vendors must apply their default legal basis
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +    -  If there is a legal basis restriction vendors must apply the publisher defined legal basis
```suggestion
    -  If there is a legal basis restriction vendors must apply the publisher defined legal basis, which is only allowed if that purpose is either declared with the allowed legal basis as default legal basis, or if that purpose was declared as flexible
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +In case the publisher disallows processing or the publisher defined legal basis is not registered by the vendor nor is the vendor flexible it may not process for that purpose. For example, if a vendo
```suggestion
In case the publisher disallows processing or in case the acceptable legal basis defined by the publisher in the restrictions is not registered by the vendor as default purpose nor is the vendor declaring that purpose as flexible, the vendor may not process personal data based on that purpose. For example, if a vendor registered legitimate interest as legal basis for a purpose and is not declaring legal basis for that purpose as flexible, it may not process in the presence of a legal basis restriction that requires consent.
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +After determining the applicable legal basis vendors must then check
```suggestion
After determining the applicable legal basis, vendors must then check:
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +Only if both signals are present for the applicable legal basis in the TC String may the vendor process for that purpose.
```suggestion
Only if both signals are positive for the applicable legal basis in the TC String may the vendor process for that purpose.
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +1. the presence of a purpose legal basis signal for the respective purpose
```suggestion
1. the presence of a purpose legal basis signal for each purpose 
```

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
Not very informed about this bit, could you share the policy references? Otherwise I'll leave it to others to check.

2020-11-24 07:36 UTC, Facens commented on TCFv2/TCF-Implementation-Guidelines.md
> +## How to determine legal bases from the TC String?<a name="detlegalbasis"></a>
@alextcone I feel this would be a great place to integrate my flow chart, which leads to the same conclusions but being it a graphical representation is probably easier to check and thus could lead to better enforcement of this tricky part of the guidelines.
Link: https://whimsical.com/tcf-vendor-decision-flow-R2kEUj1mMLJETZRE5NH9Tu
@asr-enid I think that if you also review the flow and give it your check, you'd give Alex more confidence towards moving it forward.

2020-11-25 08:53 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +For vendors or media buyers registered in the Global Vendor List, these guidelines help you understand how to determine whether you have the necessary legal bases to process a user's personal data fo
Works for me - It might be necessary to revisit the whole guidance document.

2020-11-25 08:55 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +## How to determine legal bases from the TC String?<a name="detlegalbasis"></a>
@Facens - sure lets do that, I would suggest a separate PR on this once we are done with the wording update

2020-11-25 08:58 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +Prior to processing a user’s personal data for a purpose registered in the GVL, vendors must:
Good clarification

2020-11-25 08:59 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +1.  Check if the publisher disallowed the processing for this purpose using a purpose restriction
Works for me, for/based on is something for native speaker ;)

2020-11-25 09:00 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +2.  Check if the publisher specified the applicable legal basis for this purpose using a legal basis restriction:
Okay - I don't really like the restriction language, but given its how its named overall lets use it here too

2020-11-25 09:04 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +    -  If there is a legal basis restriction vendors must apply the publisher defined legal basis
Fine - can't be said often enough ;)

2020-11-25 09:06 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +In case the publisher disallows processing or the publisher defined legal basis is not registered by the vendor nor is the vendor flexible it may not process for that purpose. For example, if a vendo
Fine with me, more elaborate description

2020-11-25 09:08 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +According to the policies of the Transparency and Consent Framework, a vendor may choose not to transmit data to another vendor for any reason, but a vendor must not transmit data to another vendor w
@Facens this is an old text element that was referring to passing a signal, this commit only changes the title.

2020-11-25 09:13 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +1.	Vendors must be registered in the Global Vendor List if they want to read or process user data in compliance with TCF or store and/or access information on a user’s device in compliance with the T
Makes sense, this was old language anyway only change should to must initially

2020-11-25 09:13 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +In order to determine if they have the necessary legal basis to process a user’s personal data for a specific purpose registered in the GVL, vendors must apply all relevant signals from the TC String
Works, using registered twice is not good anyhow

2020-11-25 09:14 UTC, asr-enid commented on TCFv2/TCF-Implementation-Guidelines.md
> +The relevant signals are: The applicable version of the GVL, the publisher restriction signal, the purpose legal basis signal and the vendor legal basis signal.
Work, makes the relation to the TC String more explicit

2020-12-09 15:52 UTC, asr-enid commented
@Facens ready to approve? I think Alex wanted one more approval before merging

2020-12-10 14:01 UTC, Facens approved these changes

2020-12-10 14:01 UTC, Facens commented
@asr-enid approved!

2020-12-14 19:34 UTC, alextcone approved these changes

2020-12-14 19:38 UTC, merged