clearly handle no cookie use
InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework pull request #261
Opened 2021-02-05 23:05 UTC by alextcone

Currently, IAB Europe, the managing organization (MO) for TCF is using the value -100 as a proxy to indicate a GVL vendor does not use cookies of any kind (including session cookies). This pull request is meant to add a clear indication to CMPs and subsequently to users that a vendor does not use cookies of any kind.

2021-02-08 19:27 UTC, janwinkler approved these changes

2021-02-18 04:20 UTC, HeinzBaumann commented
I think this looks good. I do have a question though. I see that cookieMaxAgeSeconds is not optional. Is this now optional in all cases or does it need to be set when usesCookies is set to true?  Do we need to clarify that in the documentation?

2021-02-18 23:04 UTC, HeinzBaumann commented
Suggestion was made by Anne Goodman:
Anne Goodman
3:12 AM (11 hours ago)
to alex.cone@iabtechlab.com, me

Hi there,

In preparation for the call covering off the point that Heinz you raise on GitHub ref pt 5 below (see highlighted)

Heinz comment
I think this looks good. I do have a question though. I see that cookieMaxAgeSeconds is not optional. Is this now optional in all cases or does it need to be set when usesCookies is set to true? Do we need to clarify that in the documentation?

The GVL currently asks registering vendors to indicate 

Not applicable - no cookies used

The completion of this field would drive the outcome usesCookies set false and at the same time field cookieMaxAgeSeconds* is no longer required. If they did not complete the field usesCookies then this field would be set to true and the cookieMaxAgeSeconds* is required.

Therefore the cookieMaxAgeSeconds* is not required if usesCookies set false

Should the documentation that currently reads "required" and "optional" actually read "required" and "not required" (therefore making the documentation clearer reflecting on Heinz point)?

<td><strong>required</strong> 
<td><strong>optional</strong>

Anne Goodman @aol.com 
07802 784418

2021-02-24 12:54 UTC, lon-pilot-mpf commented on TCFv2/IAB Tech Lab - Device storage duration and access disclosure.md
> +   <td><strong>optional</strong>
Given Anne's comment, perhaps "Required if useCookies is set to True, else optional" is better here?

2021-02-25 13:00 UTC, tla-sirdata commented
> A negative number or a 0 indicate session storage similar to the Set-Cookie spec

Should we update that line since a negative number is no longer possible ?

2021-02-25 16:08 UTC, HeinzBaumann requested changes

2021-02-25 16:08 UTC, HeinzBaumann commented on TCFv2/IAB Tech Lab - Device storage duration and access disclosure.md
> +   <td><strong>optional</strong>
Agreed. @alextcone can you do that change in the doc, please?

2021-02-27 08:56 UTC, BorisSambil commented on TCFv2/IAB Tech Lab - Device storage duration and access disclosure.md
> +   <td><strong>optional</strong>
I think it’s definitely good to have that extra attribute usesCookies true|false and only integers for cookieMaxAgeSeconds. But that raises following question for me: The MO officially announced that cookieMaxAgeSeconds will be null in the gvl for the case when the vendor checked „I don’t use cookies“ (and postponed the gvl change until March 11th) - If we go with this PR and make the cookieMaxAgeSeconds optional - I dont see that the null value makes sense. (And don’t think the gvl change should happen if we shortterm apply this pr)

2021-02-28 20:16 UTC, alextcone commented on TCFv2/IAB Tech Lab - Device storage duration and access disclosure.md
> +   <td><strong>optional</strong>
@HeinzBaumann and @lon-pilot-mpf, resolving now.

2021-03-02 01:47 UTC, HeinzBaumann approved these changes

2021-03-02 01:48 UTC, HeinzBaumann approved these changes

2021-03-02 11:12 UTC, lon-pilot-mpf approved these changes

2021-03-03 03:30 UTC, dmdabbs approved these changes

2021-03-03 13:28 UTC, alextcone commented
> > A negative number or a 0 indicate session storage similar to the Set-Cookie spec
> 
> Should we update that line since a negative number is no longer possible ?
> 
> `maxAgeSeconds` should be also clarified in the disclosure object for session cookies.

@tla-sirdata - done

2021-03-03 17:54 UTC, lon-pilot-mpf commented
Hey @alextcone could you please merge master into this branch? It is a bit confusing as certain features of the master branch (e.g `cookieRefresh`) are missing.

2021-03-04 15:35 UTC, Facens requested changes
IAB Europe is now using 'cookieMaxAgeSeconds: null' as an indication that cookies are not in use. Could you please clarify why we feel the need to add the usesCookies field? I'm not against in principle, but it would be a proxy of 'cookieMaxAgeSeconds: null' and it has the drawback of increasing the size of the GVL.

2021-03-04 15:35 UTC, Facens commented on TCFv2/IAB Tech Lab - Device storage duration and access disclosure.md
> +   <td><strong>required if useCookies is set to true, else optional</strong>
```suggestion
   <td><strong>required if usesCookies is set to true, else optional</strong>
```

2021-03-09 19:54 UTC, alextcone commented
> IAB Europe is now using 'cookieMaxAgeSeconds: null' as an indicator that cookies are not used. Could you please clarify why we feel the need to add the usesCookies field? I'm not against it in principle, but it would be a proxy of 'cookieMaxAgeSeconds: null' and it has the drawback of increasing the size of the GVL.

IAB Europe is now aligned with the change that makes this a clear, new field instead of using null or a negative number on a different field to mean the same thing. From a note this morning Anne Goodman at IAB Europe sent:

> From: Anne Goodman
> Reply-To: Anne Goodman 
> Date: Tuesday, March 9, 2021 at 1:54 AM
> To: Alex Cone
> Subject: Re: GVL field CookiesMaxAge - FINAL
> ...
> 
> TO BE CLEAR - I will update the GVL JSON so that it reflects the commit on usesCookies and will be populated with the additional field in the GVL based on vendors checking the "Not applicable - no cookies used" (true) or not (false) in their registration. When this field is set to true, the cookieMaxAgeSeconds field be NULL instead of being set to -100 by default.
> 
> The above has been actioned and should be live on 11th Thursday. 
> 
> ...
> 
> Thanks
> Anne

2021-03-09 19:55 UTC, merged