Vendor Fields relating to the Planet49 ruling
InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework pull request #311
Opened 2022-02-01 18:06 UTC by anderagakura

Move the current vendor fields relating to the Planet 49 ruling from the existing Device Storage Access & Disclosure tech spec to this core spec

2022-02-04 08:17 UTC, tla-sirdata requested changes
Some links must be added/updated

2022-02-04 08:17 UTC, tla-sirdata commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +In its Planet49 judgment (available here), the Court of Justice of the European Union (CJEU) ruled that the requirements for informed consent under Article 5(3) of the ePrivacy Directive include the
Two missing links in this paragraph : 
- _here_ should point to http://curia.europa.eu/juris/document/document.jsf;jsessionid=DA9630A1B5B38A1B6EFD5C9CC1DCD815?text=&docid=218462&pageIndex=0&doclang=EN&mode=lst&dir=&occ=first&part=1&cid=8222720
- <sup>_[1]_</sup> should point to the added footnote 1

2022-02-04 08:17 UTC, tla-sirdata commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +  <tr><td><code>deviceStorageDisclosureURL</code></td><td>boolean</td><td>This required field is a secure URL to a vendor-hosted resource that adheres to the structure, content and serving described
Based on [PR 313](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/313), the URL for Vendor Device Storage & Operational Disclosures is https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/tree/master/TCFv2/Vendor%20Device%20Storage%20%26%20Operational%20Disclosures.md

2022-02-04 16:01 UTC, anderagakura commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +In its Planet49 judgment (available here), the Court of Justice of the European Union (CJEU) ruled that the requirements for informed consent under Article 5(3) of the ePrivacy Directive include the
Update [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/311/commits/4785f9d16f71484962024fcb407c036bb0eca30b)

2022-02-04 16:01 UTC, anderagakura commented on TCFv2/IAB Tech Lab - Consent string and vendor list formats v2.md
> +  <tr><td><code>deviceStorageDisclosureURL</code></td><td>boolean</td><td>This required field is a secure URL to a vendor-hosted resource that adheres to the structure, content and serving described
Update [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/311/commits/4785f9d16f71484962024fcb407c036bb0eca30b)

2022-02-12 00:20 UTC, HeinzBaumann approved these changes

2022-03-02 10:04 UTC, merged