Vendor Device Storage and Operational Disclosures
InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework pull request #313
Opened 2022-02-01 22:44 UTC by anderagakura

Vendor Device Storage and Operational Disclosures that supersedes the current Device Storage Access and Disclosure specification

2022-02-04 08:38 UTC, tla-sirdata requested changes

2022-02-04 08:38 UTC, tla-sirdata commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +<table>
Some fields are specified as optional/required in both "scope" and "description" columns, which can be confusing. It should only be described in the "scope" column (like `cookieRefresh`)

Field names should be highlighted.

2022-02-04 08:38 UTC, tla-sirdata commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +<table>
Field names should be highlighted.

2022-02-04 08:38 UTC, tla-sirdata commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +**Final v.2.0 | August 2019, Updated September 2021**
Date must be updated.

2022-02-04 16:07 UTC, anderagakura commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +<table>
Quick question : Why should we highlight the field names while in the other pages (example [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md)), it's not the case?

2022-02-04 16:17 UTC, tla-sirdata commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +<table>
It's just to make it easier to read and help understand that they are "values" and not descriptive text. Thanks

2022-02-07 08:34 UTC, anderagakura commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +<table>
Done [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/313/commits/206bfa01eee11f008882676c37d757bc98a83f98)

2022-02-07 08:34 UTC, anderagakura commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +<table>
Done [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/313/commits/206bfa01eee11f008882676c37d757bc98a83f98)

2022-02-07 08:34 UTC, anderagakura commented on TCFv2/Vendor Device Storage & Operational Disclosures.md
> +**Final v.2.0 | August 2019, Updated September 2021**
Done [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/pull/313/commits/206bfa01eee11f008882676c37d757bc98a83f98)

2022-02-12 00:26 UTC, HeinzBaumann approved these changes

2022-03-11 16:05 UTC, merged